include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude: [lib/**.freezed.dart, lib/**.g.dart]
  errors:
    invalid_annotation_target: ignore
    argument_type_not_assignable: ignore
