name: mpcheckout
description: An unofficial package of MercadoPago Mobile Checkout.
version: 0.1.0
repository: https://github.com/Gonzaa25/mpcheckout

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gga.dev.mpcheckout
        pluginClass: MpcheckoutPlugin
      ios:
        pluginClass: MpcheckoutPlugin
