name: mpcheckout
description: An unofficial package of MercadoPago Mobile Checkout.
version: 1.1.1
repository: https://github.com/Gonzaa25/mpcheckout

funding:
  - https://cafecito.app/ggauto

screenshots:
  - description: 'Usage example'
    path: mpcheckout-example.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.gga.dev.mpcheckout
        pluginClass: MpcheckoutPlugin
